### ISSUE TITLE
Easiness of how to use geofront in mac

### ISSUE THREAD

**Issue by williamlidev** [spoqa/geofront#16]
Trying to use geofront as ssh key management system, however, encountered some problems during installation and when tried to start one server. Emailed Minhee about this issue, here is email which contained the description of the issues encountered.

> Hi, William. I will look into this and get back to you. It would be better if you file a new issue in GitHub issues. 🙏🏼

>On Tue, Apr 11, 2017 at 17:34 Wei Li <william.li.dev@gmail.com> wrote:
>Hi Minhee,

>Good afternoon, my name is Wei Li, I have been experimenting with geofront as a ssh key management system, however, encountered some problems while trying it out, here are some questions.

>1. I installed geofront with "pip install geofront" command, then I ran geofront -p 8080 example.cfg.py, however, it told me some valid syntax, I changed the geofront file, from #!/usr/local/opt/python/bin/python2.7 to #!/usr/local/opt/python3/bin/python3.6, seems solved this problem, is this correct?

>2. Then I ran the command again, it shows Exception: Provider constant "EC2_US_WEST" has been removed. New constant is now called "EC2".For more information on this change and how to modify your code to work with it, please visit: https://s.apache.org/lc0140un, so I browsed website, and changed it from EC2_US_WEST to us-west-1, is this correct? Because I encountered another problem after this change, TimeoutError: [Errno 60] Unable to load configuration file (Operation timed out).

>How should I use the software to make it work? It is not exactly as what the doc said to make it work anyway...

>Look forward to hearing back from you, if possible, we can video chat via google to figure this out, thanks!

>Best regards,
>William

Hope it will be easier to use the software. :)

**Comment by dahlia** [comment]
1.  It seems your `pip` is for Python 2.7.  Unless you're in a [pyvenv][] or virtualenv w/ Python 3, the pip command for Python 3 is `pip3`. I doubt whether your Geofront is correctly installed.  Recommend to uninstall the installed one, and reinstall new one using `pip3` command: `pip uninstall -y Geofront && pip3 install Geofront`.
 2.  Yes, apache-libcloud deprecated `EC2_*` region constants and has provided `EC2` instead since then.

The above should be changed in docs as well.  I will update them.

[pyvenv]: https://docs.python.org/3/whatsnew/3.3.html#pep-405
